name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      # TO COMPLETE   
  job2:
    name: npm install
    uses: actions/checkout@v3.4.0
    uses: actions/setup-node@v3
    with:
      node-version: lts/*
    run: npm install
   