name: Call a reusable workflow

on:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
      uses: .github/workflows/ex1.yml
      with:
        config-path: .github/labeler.yml
      version:
        node: 14

  