name: npm test
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    strategy:
      matrix:
        version: [14, 16]
        os: [ubuntu-latest, ubuntu-18.04]
        include:
      - version: 14
        os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.version }}
        - name: run install
          shell: bash
          run: |
            npm install
            npm test